// Default doesn't make sense for a type whose constructor is random.
#![allow(clippy::new_without_default)]

use std::fmt;

use serde::{Deserialize, Serialize, Serializer};
use uuid::Uuid;

/// A randomly generated ID generated by Rojo during a serve session.
///
/// If the session ID of the server changes between requests, that indicates
/// that a new server has started up and the session should be terminated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
pub struct SessionId(Uuid);

impl SessionId {
    pub fn new() -> SessionId {
        SessionId(Uuid::new_v4())
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, writer: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(writer, "{}", self.0)
    }
}

impl Serialize for SessionId {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.0.hyphenated().encode_lower(&mut Uuid::encode_buffer()))
    }
}
